version: "3.9"

services:
  transaction-aggregation-api:
    container_name: transaction-aggregation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
